### ISSUE TITLE
Error in track by detector PRBNet on MOT20: RuntimeError

### ISSUE THREAD

**Issue by iTruffle** [WWangYuHsiang/SMILEtrack#7]
Thanks for your great work.
I can successfully track by detector YOLOX on MOT17 and MOT20 datasets, and successfully track by detector PRBNet on MOT17 dataset. However, when I track by detector PRBNet on MOT20 dataset with the weight "/pretrained/yolov7-d6-mot20.pt", I get an error like this:"RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory". This weight is downloaded from this [link](https://drive.google.com/file/d/1KyRJNgfApv3m7cHdW7Ekt87pxrs_3ozu/view).
![image](https://user-images.githubusercontent.com/80766557/226608072-ce3b1fbf-596d-4cb8-86fc-c695f8d91cdc.png)

**Comment by Melankolily** [comment]
@iTruffle I also ran into this problem about running detector yolo-v7 and PRBNet on MOT20 dataset. If you solve this problem, please let me know how. Thank you !

**Comment by iTruffle** [comment]
这个错误是权重损坏了，重新上传一下就行。
